Models/Event.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class Event
    {
        public int EventId { get; set; }

        public int EventTypeId { get; set; }

        public EventType EventType { get; set; }

        public string EventTitle { get; set; }

        public string EventBody { get; set; }

        public string EventLocation { get; set; }

        public string EventStart { get; set; }

        public string EventEnd { get; set; }

        public bool PublishEvent { get; set; }

        public Event()
        { 
        
        }
    }
}

Models/EventType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class EventType
    {
        [Key]
        public int EventTypeId { get; set; }

        public string EventTypeName { get; set; }

        public int EventDisplayOrder { get; set; }

        public int EventTypeActive { get; set; }

        public EventType()
        {

        }
    }
}

Controllers/EventDutiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class EventDutiesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventDutiesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: EventDuties
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.EventDuty.Include(e => e.Event);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: EventDuties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventDuty = await _context.EventDuty
                .Include(e => e.Event)
                .FirstOrDefaultAsync(m => m.EventDutyId == id);
            if (eventDuty == null)
            {
                return NotFound();
            }

            return View(eventDuty);
        }

        // GET: EventDuties/Create
        public IActionResult Create()
        {
            ViewData["EventId"] = new SelectList(_context.Event, "EventId", "EventTitle");
            return View();
        }

        // POST: EventDuties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventDutyId,EventId,DutyDescription")] EventDuty eventDuty)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eventDuty);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventId"] = new SelectList(_context.Event, "EventId", "EventTitle", eventDuty.EventId);
            return View(eventDuty);
        }

        // GET: EventDuties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventDuty = await _context.EventDuty.FindAsync(id);
            if (eventDuty == null)
            {
                return NotFound();
            }
            ViewData["EventId"] = new SelectList(_context.Event, "EventId", "EventTitle", eventDuty.EventId);
            return View(eventDuty);
        }

        // POST: EventDuties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventDutyId,EventId,DutyDescription")] EventDuty eventDuty)
        {
            if (id != eventDuty.EventDutyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eventDuty);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventDutyExists(eventDuty.EventDutyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventId"] = new SelectList(_context.Event, "EventId", "EventTitle", eventDuty.EventId);
            return View(eventDuty);
        }

        // GET: EventDuties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventDuty = await _context.EventDuty
                .Include(e => e.Event)
                .FirstOrDefaultAsync(m => m.EventDutyId == id);
            if (eventDuty == null)
            {
                return NotFound();
            }

            return View(eventDuty);
        }

        // POST: EventDuties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var eventDuty = await _context.EventDuty.FindAsync(id);
            _context.EventDuty.Remove(eventDuty);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventDutyExists(int id)
        {
            return _context.EventDuty.Any(e => e.EventDutyId == id);
        }
    }
}

Controllers/EventTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;

namespace WebApplication1.Models
{
    public class EventTypesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventTypesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: EventTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.EventType.ToListAsync());
        }

        // GET: EventTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventType = await _context.EventType
                .FirstOrDefaultAsync(m => m.EventTypeId == id);
            if (eventType == null)
            {
                return NotFound();
            }

            return View(eventType);
        }

        // GET: EventTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EventTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventTypeId,EventTypeName,EventDisplayOrder,EventTypeActive")] EventType eventType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eventType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(eventType);
        }

        // GET: EventTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventType = await _context.EventType.FindAsync(id);
            if (eventType == null)
            {
                return NotFound();
            }
            return View(eventType);
        }

        // POST: EventTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventTypeId,EventTypeName,EventDisplayOrder,EventTypeActive")] EventType eventType)
        {
            if (id != eventType.EventTypeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eventType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventTypeExists(eventType.EventTypeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(eventType);
        }

        // GET: EventTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventType = await _context.EventType
                .FirstOrDefaultAsync(m => m.EventTypeId == id);
            if (eventType == null)
            {
                return NotFound();
            }

            return View(eventType);
        }

        // POST: EventTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var eventType = await _context.EventType.FindAsync(id);
            _context.EventType.Remove(eventType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventTypeExists(int id)
        {
            return _context.EventType.Any(e => e.EventTypeId == id);
        }
    }
}

Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            return View(await _context.Event.ToListAsync());
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("EventId,EventType,EventTitle,EventBody,EventLocation,EventStart,EventEnd,PublishEvent")] Event @event)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Events/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("EventId,EventType,EventTitle,EventBody,EventLocation,EventStart,EventEnd,PublishEvent")] Event @event)
        {
            if (id != @event.EventId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.EventId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @event = await _context.Event.FindAsync(id);
            _context.Event.Remove(@event);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
            return _context.Event.Any(e => e.EventId == id);
        }
    }
}

Views/Events/Create.cshtml
@model WebApplication1.Models.Event

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EventTypeId" class="control-label"></label>
                <select asp-for="EventTypeId" class="form-control" asp-items="ViewBag.EventTypeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="EventTitle" class="control-label"></label>
                <input asp-for="EventTitle" class="form-control" />
                <span asp-validation-for="EventTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventBody" class="control-label"></label>
                <input asp-for="EventBody" class="form-control" />
                <span asp-validation-for="EventBody" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventLocation" class="control-label"></label>
                <input asp-for="EventLocation" class="form-control" />
                <span asp-validation-for="EventLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventStart" class="control-label"></label>
                <input type="date" asp-for="EventStart" class="form-control" />
                <span asp-validation-for="EventStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventEnd" class="control-label"></label>
                <input type="date" asp-for="EventEnd" class="form-control" />
                <span asp-validation-for="EventEnd" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="PublishEvent" /> @Html.DisplayNameFor(model => model.PublishEvent)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Events/Delete.cshtml
@model WebApplication1.Models.Event

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventBody)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventBody)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventStart)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventStart)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventEnd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventEnd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishEvent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishEvent)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EventId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Events/Details.cshtml
@model WebApplication1.Models.Event

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EventType.EventTypeName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EventType.EventTypeName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EventTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EventTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EventBody)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EventBody)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EventLocation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EventLocation)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EventStart)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EventStart)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EventEnd)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EventEnd)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublishEvent)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublishEvent)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.EventId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Events/Edit.cshtml
@model WebApplication1.Models.Event

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EventId" />
            <div class="form-group">
                <label asp-for="EventTypeId" class="control-label"></label>
                <select asp-for="EventTypeId" class="form-control" asp-items="ViewBag.EventTypeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="EventTitle" class="control-label"></label>
                <input asp-for="EventTitle" class="form-control" />
                <span asp-validation-for="EventTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventBody" class="control-label"></label>
                <input asp-for="EventBody" class="form-control" />
                <span asp-validation-for="EventBody" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventLocation" class="control-label"></label>
                <input asp-for="EventLocation" class="form-control" />
                <span asp-validation-for="EventLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventStart" class="control-label"></label>
                <input type="date" asp-for="EventStart" class="form-control" />
                <span asp-validation-for="EventStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventEnd" class="control-label"></label>
                <input type="date" asp-for="EventEnd" class="form-control" />
                <span asp-validation-for="EventEnd" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="PublishEvent" /> @Html.DisplayNameFor(model => model.PublishEvent)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Events/Index.cshtml
@model IEnumerable<WebApplication1.Models.Event>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div>
    <a class="btn btn-secondary" asp-area="" asp-controller="EventDuties" asp-action="Create">Edit Duties</a>
</div>
<div>
    <a class="btn btn-secondary" asp-area="" asp-controller="EventTypes" asp-action="Index">Manage Event Types</a>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EventType.EventTypeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventBody)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventStart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventEnd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishEvent)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.EventType.EventTypeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EventTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EventBody)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EventLocation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EventStart)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EventEnd)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublishEvent)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.EventId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.EventId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.EventId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>