Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class Project
    {
        [Key]
        public int ProjectId { get; set; }

        public string ProjectName { get; set; }

        public string ProjectShortDesc { get; set; }

        public string ProjectLongDesc { get; set; }

        public string ProjectPostedDate { get; set; }

        public string ProjectCreationDate { get; set; }

        public IEnumerable<Category> Categories { get; set; }
        public IEnumerable<Framework> Frameworks { get; set; }

        public Project()
        {

        }

    }

}

Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Category.Include(p => p.Colour);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .Include(p => p.Colour)
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            ViewData["CategoryColourId"] = new SelectList(_context.Colour, "ColourId", "ColourName");
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,CategoryName,ColourId")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["CategoryColourId"] = new SelectList(_context.Colour, "ColourId", "ColourName", category.ColourId);
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            ViewData["CategoryColourId"] = new SelectList(_context.Colour, "ColourId", "ColourName", category.ColourId);
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId,CategoryName,ColourId")] Category category)
        {
            if (id != category.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryColourId"] = new SelectList(_context.Colour, "ColourId", "ColourName", category.ColourId);
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .Include(p => p.Colour)
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Category.FindAsync(id);
            _context.Category.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.CategoryId == id);
        }
    }
}

Controllers/FrameworksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class FrameworksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FrameworksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Frameworks
        public async Task<IActionResult> Index()
        {
            return View(await _context.Framework.ToListAsync());
        }

        // GET: Frameworks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var framework = await _context.Framework
                .FirstOrDefaultAsync(m => m.FrameworkId == id);
            if (framework == null)
            {
                return NotFound();
            }

            return View(framework);
        }

        // GET: Frameworks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Frameworks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FrameworkId,FrameworkName,FrameworkIconLoc")] Framework framework)
        {
            if (ModelState.IsValid)
            {
                _context.Add(framework);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(framework);
        }

        // GET: Frameworks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var framework = await _context.Framework.FindAsync(id);
            if (framework == null)
            {
                return NotFound();
            }
            return View(framework);
        }

        // POST: Frameworks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FrameworkId,FrameworkName,FrameworkIconLoc")] Framework framework)
        {
            if (id != framework.FrameworkId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(framework);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FrameworkExists(framework.FrameworkId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(framework);
        }

        // GET: Frameworks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var framework = await _context.Framework
                .FirstOrDefaultAsync(m => m.FrameworkId == id);
            if (framework == null)
            {
                return NotFound();
            }

            return View(framework);
        }

        // POST: Frameworks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var framework = await _context.Framework.FindAsync(id);
            _context.Framework.Remove(framework);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FrameworkExists(int id)
        {
            return _context.Framework.Any(e => e.FrameworkId == id);
        }
    }
}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProjectsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {
            return View(await _context.Project.ToListAsync());
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Project
                .FirstOrDefaultAsync(m => m.ProjectId == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProjectId,ProjectName,ProjectShortDesc,ProjectLongDesc,ProjectPostedDate,ProjectCreationDate")] Project project)
        {
            if (ModelState.IsValid)
            {
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Project.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProjectId,ProjectName,ProjectShortDesc,ProjectLongDesc,ProjectPostedDate,ProjectCreationDate")] Project project)
        {
            if (id != project.ProjectId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.ProjectId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Project
                .FirstOrDefaultAsync(m => m.ProjectId == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var project = await _context.Project.FindAsync(id);
            _context.Project.Remove(project);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(int id)
        {
            return _context.Project.Any(e => e.ProjectId == id);
        }
    }
}

Views/Projects/Create.cshtml
@model WebApplication1.Models.Project

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProjectName" class="control-label"></label>
                <input asp-for="ProjectName" class="form-control" />
                <span asp-validation-for="ProjectName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectShortDesc" class="control-label"></label>
                <input asp-for="ProjectShortDesc" class="form-control" />
                <span asp-validation-for="ProjectShortDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectLongDesc" class="control-label"></label>
                <input asp-for="ProjectLongDesc" class="form-control" />
                <span asp-validation-for="ProjectLongDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectPostedDate" class="control-label"></label>
                <input type="date" asp-for="ProjectPostedDate" class="form-control" />
                <span asp-validation-for="ProjectPostedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectCreationDate" class="control-label"></label>
                <input type="date" asp-for="ProjectCreationDate" class="form-control" />
                <span asp-validation-for="ProjectCreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Projects/Delete.cshtml
@model WebApplication1.Models.Project

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectShortDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectShortDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectLongDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectLongDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPostedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectPostedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectCreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectCreationDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProjectId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Projects/Details.cshtml
@model WebApplication1.Models.Project

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectShortDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectShortDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectLongDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectLongDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPostedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectPostedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectCreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectCreationDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProjectId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Projects/Edit.cshtml
@model WebApplication1.Models.Project

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProjectId" />
            <div class="form-group">
                <label asp-for="ProjectName" class="control-label"></label>
                <input asp-for="ProjectName" class="form-control" />
                <span asp-validation-for="ProjectName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectShortDesc" class="control-label"></label>
                <input asp-for="ProjectShortDesc" class="form-control" />
                <span asp-validation-for="ProjectShortDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectLongDesc" class="control-label"></label>
                <input asp-for="ProjectLongDesc" class="form-control" />
                <span asp-validation-for="ProjectLongDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectPostedDate" class="control-label"></label>
                <input type="date" asp-for="ProjectPostedDate" class="form-control" />
                <span asp-validation-for="ProjectPostedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectCreationDate" class="control-label"></label>
                <input type="date" asp-for="ProjectCreationDate" class="form-control" />
                <span asp-validation-for="ProjectCreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Projects/Index.cshtml
@model IEnumerable<WebApplication1.Models.Project>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="flex-fill">
    <div>
        <a class="btn btn-secondary" asp-area="" asp-controller="ProjectCategories" asp-action="Index">Link Categories</a>
    </div>
    <div>
        <a class="btn btn-secondary" asp-area="" asp-controller="ProjectFrameworks" asp-action="Index">Link Frameworks</a>
    </div>
    <div>
        <a class="btn btn-secondary" asp-area="" asp-controller="Categories" asp-action="Index">Edit Categories</a>
    </div>
    <div>
        <a class="btn btn-secondary" asp-area="" asp-controller="Frameworks" asp-action="Index">Edit Frameworks</a>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProjectName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProjectShortDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProjectLongDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProjectPostedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProjectCreationDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectShortDesc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectLongDesc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectPostedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectCreationDate)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ProjectId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ProjectId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ProjectId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>